FROM bnbalsamo/flask_stack
ENV APP_NAME=rec_api
ARG MONGO_HOST
ARG MONGO_DB
ARG SECRET_KEY="setThisAtBuildTime"
ARG MONGO_PORT="27017"
ARG VERBOSITY="WARN"
ENV \
    REC_API_MONGO_HOST=${MONGO_HOST} \
    REC_API_MONGO_PORT=${MONGO_PORT} \
    REC_API_MONGO_DB=${MONGO_DB} \
    REC_API_VERBOSITY=${VERBOSITY} \
    REC_API_SECRET_KEY=${SECRET_KEY}
